package Section_2.Chapter_2_Exceptions

fun erroneousCode(){
    val i= "1$".toInt()
}
fun main(){
    erroneousCode()
}